name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ssh.pythonanywhere.com
          username: yourusername
          key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
          script: |
            cd ~/yourproject
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            touch ~/yourusername.pythonanywhere.com_wsgi.py
