name: Deploy to PythonAnywhere

on:
  pull_request:
    branches:
      - LastCICD  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install openssh-client

      - name: Deploy to PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.SSH_PRIVATE_USERNAME }}
          PA_API_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
          ssh ${PA_USERNAME}@ssh.pythonanywhere.com << EOF
            cd your-repo
            source venv/bin/activate
            git pull origin master
            touch /var/www/${PA_USERNAME}_pythonanywhere_com_wsgi.py
          EOF
