name: Deploy Django to PythonAnywhere

on:
  pull_request:
    branches:
      - Newdev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ssh.pythonanywhere.com
          username: priya100898
          key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
          script: |
            cd ~/CvFiltering
            git pull origin Newdev
            source venv/bin/activate
            
