name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - dev  # Auto deploy when changes are pushed to 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust based on your project needs

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Upload Code to PythonAnywhere
        run: |
          echo "Uploading files to PythonAnywhere..."
          scp -r ./* ${{ secrets.PA_USERNAME }}@ssh.pythonanywhere.com:/home/${{ secrets.PA_USERNAME }}/cv_filtering

      - name: Restart PythonAnywhere Web App
        run: |
          echo "Restarting web app on PythonAnywhere..."
          curl -X POST -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
            "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/Priya100898.pythonanywhere.com/reload/"
