name: Django CI/CD

on:
  pull_request:
    branches:
      - LastCICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      

      - name: Deploy to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/priya100898/webapps/reload/"
          -H "Authorization: Token $PA_API_TOKEN"
